#!/usr/bin/env perl

use strict;
use 5.010;
use LWP::UserAgent;
use HTML::TableExtract;

use lib '.';
use MinecraftStatsParser;

use Data::Dump;

my $player_name = shift
    or die "Usage: $0 playername";

say Data::Dump::dump(
    MinecraftStatsParser::get_stats($player_name)
);

